blank_issues_enabled: false
contact_links:
  - name: Bot Invite Link
    url: https://discordapp.com/oauth2/authorize?client_id=1108279646165942363&scope=bot&permissions=27712
    about: Click this link to invite the bot to your server
